### ISSUE TITLE
Contrôleur : afficher dernier résultat -> orienter le contrôle

### ISSUE THREAD

**Issue by Guillaume35** [pebble-solutions/App-QSE-controle-frontend#85]
**customer and user**
FE - contrôleur

**Scrum brief**
En tant que contrôleur, je veux afficher les informations des derniers résultats pour un opérateur sur chaque item d'un contrôle.

**Brief**
Je veux vérifier rapidement quels sont les points à vigiler afin d'orienter le KN.

**Additional information**

**Team**
@killiankopp 

**Code indication**

**Todo**
- [x] @TigrouForMatic : réfléchir aux routes et écrire les specs (ici)
- [x] @TigrouForMatic : faire valider les specs
- [x] @TigrouForMatic : créer les routes

![monitoring](https://user-images.githubusercontent.com/945411/228265766-c3463409-3b1d-4250-a58d-138f4cdd1aad.png)

**Comment by Ambrelaoh** [comment]
test Ambre commentaire, issue ouverte par quelqu'un d'autre.

**Comment by TigrouForMatic** [comment]
Pr feat-SAMI 
Back and front OK -- Finished and tested 
Enh front possible but its fonctionnal
